version: 0.1.1
source:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: {{ env_var('SOURCE_POSTGRES_DB') }}
  POSTGRES_SCHEMA: {{ env_var('SOURCE_POSTGRES_SCHEMA') }}
  POSTGRES_USER: {{ env_var('SOURCE_POSTGRES_USER') }}
  POSTGRES_PASSWORD: {{ env_var('SOURCE_POSTGRES_PASSWORD') }}
  POSTGRES_HOST: {{ env_var('SOURCE_POSTGRES_HOST') }}
  POSTGRES_PORT: {{ env_var('SOURCE_POSTGRES_PORT') }}
destination:
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: {{ env_var('DWH_POSTGRES_DB') }}
  POSTGRES_SCHEMA: {{ env_var('DWH_POSTGRES_SCHEMA') }}
  POSTGRES_USER: {{ env_var('DWH_POSTGRES_USER') }}
  POSTGRES_PASSWORD: {{ env_var('DWH_POSTGRES_PASSWORD') }}
  POSTGRES_HOST: {{ env_var('DWH_POSTGRES_HOST') }}
  POSTGRES_PORT: {{ env_var('DWH_POSTGRES_PORT') }}
